# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required
apt_packages:
- unixodbc-dev
- libarchive-dev

script: 
  - |
    R CMD build .
    travis_wait 120 R CMD check pnadc*tar.gz
    
after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
# show memory usage again
- sudo free -m -t
# show actions of the OOM killer
- sudo dmesg

r_github_packages:
 - jimhester/archive
 - ajdamico/lodown


before_install:
# shutdown servies on Travis, which may have a memory impact
# show memory usage before and after shutdown of services
- sudo service --status-all
- sudo free -m -t
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- sudo free -m -t

env:
 - this_sample_break=1
 - this_sample_break=2
 - this_sample_break=3
 - this_sample_break=4
 - this_sample_break=5
 - this_sample_break=6
 - this_sample_break=7
 - this_sample_break=8
 - this_sample_break=9
 - this_sample_break=10
 - this_sample_break=11
 - this_sample_break=12
 - this_sample_break=13
 - this_sample_break=14
 - this_sample_break=15
 - this_sample_break=16
 - this_sample_break=17
 - this_sample_break=18
 - this_sample_break=19
 - this_sample_break=20
 - this_sample_break=21
 - this_sample_break=22
 - this_sample_break=23
 - this_sample_break=24
 - this_sample_break=25
 - this_sample_break=26
 - this_sample_break=27
 - this_sample_break=28
 - this_sample_break=29
 - this_sample_break=30
 - this_sample_break=31
 - this_sample_break=32
 - this_sample_break=33
 - this_sample_break=34
 - this_sample_break=35
 - this_sample_break=36
 - this_sample_break=37
 - this_sample_break=38
 - this_sample_break=39
 - this_sample_break=40
 - this_sample_break=41
 - this_sample_break=42
 - this_sample_break=43
 - this_sample_break=44
 - this_sample_break=45
 - this_sample_break=46
 - this_sample_break=47
 - this_sample_break=48
 - this_sample_break=49
 - this_sample_break=50
